version: '{build}'
skip_tags: true

environment:
  NuGetApiKey:
    secure: EaMePsm8eU/bUd1Ej83dTOAaGja/ht/3IrKC84nbZ9+dQbjeDfbTHk7nM+wp9DgE
  GitHubToken:
    secure: LznJHcvQE4ZRnDPWnayvawgr7VSpwH6ImeN6OK6tmLh5UHKdfZu6qKQ+ZBbkei73

os: WMF 5

build: false

test_script:
- ps: . .\build\Start-Build.ps1 -Task Deploy
