version: '{build}'
skip_tags: true

environment:
  BuildToolsVersion: '1.1.*'
  StatementCoverageThreshold: 100
  FunctionCoverageThreshold: 100
  #SkipUnitTests: true
  #SkipDocumentation: true
  #SkipScriptAnalysis: true
  NuGetApiKey:
    secure: EaMePsm8eU/bUd1Ej83dTOAaGja/ht/3IrKC84nbZ9+dQbjeDfbTHk7nM+wp9DgE
  GitHubToken:
    secure: LznJHcvQE4ZRnDPWnayvawgr7VSpwH6ImeN6OK6tmLh5UHKdfZu6qKQ+ZBbkei73

os: WMF 5

build: false

test_script:
- ps: >-
    $ErrorActionPreference = 'Stop';
    $Response = Invoke-RestMethod -Uri 'https://api.github.com/repos/nicholasdille/powershell-build/releases';
    $Release = $Response | Where-Object { $_.tag_name -like $env:BuildToolsVersion } | Sort-Object -Property tag_name -Descending | Select-Object -First 1;
    Write-Host -ForegroundColor Yellow -Message "Using version $($Release.tag_name) of build tools";
    Invoke-WebRequest -Uri $Release.zipball_url -OutFile Build.zip;
    Expand-Archive -Path '.\Build.zip' -DestinationPath .;
    Remove-Item -Path '.\Build.zip';
    Get-Item -Path nicholasdille-PowerShell-Build-* | Rename-Item -NewName 'Build';
    .\Build\Start-Build.ps1 -Task Deploy